export const initialTasks = [
    {
        id: 1,
        status: 'Urgent',
        taskName: 'API Integration',
        assignedTeam: 'Dev Team',
        timeRange: '10 - 11 AM',
        peopleCount: 4,
        date: 'Mon',
    },
    {
        id: 2,
        status: 'Running',
        taskName: 'Database Backup',
        assignedTeam: 'Ops Team',
        timeRange: '11 - 12 PM',
        peopleCount: 3,
        date: 'Tue',
    },
    {
        id: 3,
        status: 'Pending',
        taskName: 'UI Design',
        assignedTeam: 'Design Team',
        timeRange: '1 - 2 PM',
        peopleCount: 2,
        date: 'Wed',
    },
    {
        id: 4,
        status: 'Pending',
        taskName: 'Code Review',
        assignedTeam: 'Dev Team',
        timeRange: '2 - 3 PM',
        peopleCount: 5,
        date: 'Thu',
    },
    {
        id: 5,
        status: 'Running',
        taskName: 'Client Meeting',
        assignedTeam: 'Sales Team',
        timeRange: '3 - 4 PM',
        peopleCount: 3,
        date: 'Fri',
    },
    {
        id: 6,
        status: 'Urgent',
        taskName: 'Server Maintenance',
        assignedTeam: 'Ops Team',
        timeRange: '4 - 5 PM',
        peopleCount: 4,
        date: 'Sat',
    },
    {
        id: 7,
        status: 'Urgent',
        taskName: 'Performance Testing',
        assignedTeam: 'QA Team',
        timeRange: '9 - 10 AM',
        peopleCount: 2,
        date: 'Sun',
    },
    {
        id: 8,
        status: 'Running',
        taskName: 'Documentation',
        assignedTeam: 'Dev Team',
        timeRange: '5 - 6 PM',
        peopleCount: 1,
        date: 'Mon',
    },
];
